from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .diagnostics import Diagnostic
from .schema_tools import check_schema_files

SUPPORTED_CONFIG_TYPES={
    "sldl.project": {
        "title": "SLDL project configuration",
        "description": "Build one or more SLDL documents into one or more outputs.",
        "required": ["config_type", "documents"],
        "important": ["version", "output_dir", "schema", "schemas", "export_config", "toc", "latex", "mermaid_mode", "latex_build_config", "documents", "write_manifest"],
    },
    "sldl.schema": {
        "title": "SLDL schema configuration",
        "description": "Define document types, allowed nodes, semantic rules, and logic rules.",
        "required": ["config_type"],
        "important": ["schema_version", "document_types", "node_rules", "object_classes", "logic_rules"],
    },
    "sldl.export_labels": {
        "title": "SLDL export label configuration",
        "description": "Customize labels used by Markdown, HTML, and LaTeX exporters.",
        "required": ["config_type"],
        "important": ["html_lang", "labels"],
    },
    "sldl.latex_build": {
        "title": "SLDL LaTeX build configuration",
        "description": "Configure how a .tex file is compiled into PDF.",
        "required": ["config_type"],
        "important": ["dry_run", "capture_output", "timeout_sec", "work_dir", "output_dir", "job_name", "pdf_path", "engine", "dvi_to_pdf", "steps", "cleanup"],
    },
    "sldl.template_manifest": {
        "title": "SLDL template manifest",
        "description": "Declare file-based templates that can be used by template commands.",
        "required": ["config_type", "templates"],
        "important": ["version", "templates"],
    },
    "sldl.build_manifest": {
        "title": "SLDL build manifest",
        "description": "Record outputs and diagnostics generated by project build.",
        "required": ["config_type", "documents"],
        "important": ["project", "version", "documents"],
    },
    "sldl.template_reference": {
        "title": "SLDL generated template reference",
        "description": "Record template reference data generated from a template manifest.",
        "required": ["config_type", "templates"],
        "important": ["version", "language", "templates"],
    },
    "sldl.release_check": {
        "title": "SLDL release check configuration",
        "description": "Declare files, configs, CLI commands, projects, and golden snapshots for release quality checks.",
        "required": ["config_type"],
        "important": ["version", "base_dir", "required_files", "forbidden_paths", "forbidden_globs", "config_files", "commands", "commands[].expect_failure", "project_files", "build_project_files", "build_manifest_files", "golden_snapshot", "compileall", "compile_paths"],
    },
    "sldl.release_manifest": {
        "title": "SLDL release quality manifest",
        "description": "Record the results of a release quality check run.",
        "required": ["config_type", "checks", "summary"],
        "important": ["version", "target", "base_dir", "python", "checks", "summary"],
    },
    "sldl.snapshot_manifest": {
        "title": "SLDL golden file snapshot manifest",
        "description": "Record SHA-256 hashes and sizes for golden files used in regression checks.",
        "required": ["config_type", "files"],
        "important": ["version", "files"],
    },
}

KNOWN_OUTPUT_FORMATS={"json", "sldj", "markdown", "html", "latex", "bibtex", "mermaid", "logic-markdown", "logic-mermaid", "pdf", "latex-pdf"}
KNOWN_CITATION_STYLES={"numeric", "ieee", "apa", "author-year"}
KNOWN_LATEX_KEYS={"profile", "engine", "document_class", "class_options", "geometry", "hyperref", "sloppy", "table_font", "top_level", "code_environment", "figure_width", "code_font_size", "mermaid_mode", "toc", "latex_profile", "latex_engine", "latex_class", "latex_class_options", "latex_geometry", "latex_hyperref", "latex_sloppy", "latex_table_font", "latex_top_level", "latex_code_environment", "latex_figure_width", "latex_code_font_size", "latex_mermaid_mode", "latex_toc"}
KNOWN_TABLE_FONT_VALUES={"none", "normalsize", "small", "footnotesize", "scriptsize"}
KNOWN_TOP_LEVEL_VALUES={"section", "chapter"}
KNOWN_CODE_ENV_VALUES={"lstlisting", "verbatim"}
KNOWN_MERMAID_MODE_VALUES={"code", "placeholder", "external-image"}


def load_config_json(path: str | Path) -> tuple[dict[str, Any] | None, list[Diagnostic]]:
    path=Path(path)
    try:
        source=path.read_text(encoding="utf-8")
    except OSError as exc:
        return None, [Diagnostic("error", "E_CONFIG_FILE_READ", f"Cannot read config file: {path} ({exc})")]
    try:
        data=json.loads(source)
    except json.JSONDecodeError as exc:
        return None, [Diagnostic("error", "E_CONFIG_JSON", f"Invalid JSON in config file: {path}: {exc.msg}", exc.lineno, exc.colno)]
    if(not isinstance(data, dict)):
        return None, [Diagnostic("error", "E_CONFIG_ROOT", "Config root must be a JSON object")]
    return data, []


def detect_config_type(data: dict[str, Any]) -> tuple[str | None, Diagnostic | None]:
    value=data.get("config_type")
    if(isinstance(value, str) and value.strip()):
        return value.strip(), None
    inferred=None
    if("documents" in data and "project" in data):
        inferred="sldl.build_manifest"
    elif("documents" in data):
        inferred="sldl.project"
    elif("document_types" in data or "logic_rules" in data or "node_rules" in data or "object_classes" in data):
        inferred="sldl.schema"
    elif("engine" in data or "dvi_to_pdf" in data or "steps" in data or "cleanup" in data):
        inferred="sldl.latex_build"
    elif("checks" in data and "summary" in data):
        inferred="sldl.release_manifest"
    elif("files" in data and any(isinstance(item, dict) and "sha256" in item for item in data.get("files", []) if isinstance(data.get("files"), list))):
        inferred="sldl.snapshot_manifest"
    elif("project_files" in data or "build_project_files" in data or "golden_snapshot" in data):
        inferred="sldl.release_check"
    elif("templates" in data and data.get("config_type")=="sldl.template_reference"):
        inferred="sldl.template_reference"
    elif("templates" in data):
        inferred="sldl.template_manifest"
    elif("labels" in data or "html_lang" in data):
        inferred="sldl.export_labels"
    if(inferred):
        return inferred, Diagnostic("warning", "W_CONFIG_TYPE_MISSING", f"config_type is missing; inferred {inferred}")
    return None, Diagnostic("error", "E_CONFIG_TYPE_MISSING", "config_type is missing and could not be inferred")


def check_config_file(path: str | Path, expected_type: str | None = None, check_paths: bool = True) -> list[Diagnostic]:
    path=Path(path)
    data,diagnostics=load_config_json(path)
    if(data is None):
        return diagnostics
    config_type,inferred_diag=detect_config_type(data)
    if(inferred_diag):
        diagnostics.append(inferred_diag)
    if(not config_type):
        return diagnostics
    if(config_type not in SUPPORTED_CONFIG_TYPES):
        diagnostics.append(Diagnostic("error", "E_CONFIG_TYPE_UNKNOWN", f"Unknown config_type: {config_type}"))
        return diagnostics
    if(expected_type and config_type!=expected_type):
        diagnostics.append(Diagnostic("error", "E_CONFIG_TYPE_MISMATCH", f"Expected {expected_type}, got {config_type}"))
    diagnostics.extend(_check_common_metadata(data, config_type))
    base_dir=path.parent
    if(config_type=="sldl.schema"):
        diagnostics.extend(check_schema_files([path]))
    elif(config_type=="sldl.project"):
        diagnostics.extend(_check_project_config(data, base_dir, check_paths))
    elif(config_type=="sldl.export_labels"):
        diagnostics.extend(_check_export_labels_config(data))
    elif(config_type=="sldl.latex_build"):
        diagnostics.extend(_check_latex_build_config(data))
    elif(config_type=="sldl.template_manifest"):
        diagnostics.extend(_check_template_manifest(data, base_dir, check_paths, path))
    elif(config_type=="sldl.template_reference"):
        diagnostics.extend(_check_template_reference(data))
    elif(config_type=="sldl.build_manifest"):
        diagnostics.extend(_check_build_manifest(data))
    elif(config_type=="sldl.release_check"):
        diagnostics.extend(_check_release_check_config(data, base_dir, check_paths))
    elif(config_type=="sldl.release_manifest"):
        diagnostics.extend(_check_release_manifest(data))
    elif(config_type=="sldl.snapshot_manifest"):
        diagnostics.extend(_check_snapshot_manifest(data, base_dir, check_paths))
    return diagnostics


def config_summary(path: str | Path) -> dict[str, Any]:
    data,diagnostics=load_config_json(path)
    if(data is None):
        return {"path": str(path), "config_type": None, "diagnostics": [d.to_dict() for d in diagnostics]}
    config_type,inferred_diag=detect_config_type(data)
    if(inferred_diag):
        diagnostics.append(inferred_diag)
    summary={
        "path": str(path),
        "config_type": config_type,
        "description": data.get("description", ""),
        "version": data.get("version", data.get("schema_version", "")),
        "top_level_keys": sorted(data.keys()),
        "diagnostics": [d.to_dict() for d in diagnostics],
    }
    if(config_type=="sldl.project"):
        docs=data.get("documents") if(isinstance(data.get("documents"), list)) else []
        summary["documents"]=len(docs)
        summary["outputs"]=sum(len(doc.get("outputs", [])) for doc in docs if(isinstance(doc, dict)))
    elif(config_type=="sldl.schema"):
        doc_types=data.get("document_types") if(isinstance(data.get("document_types"), dict)) else {}
        summary["document_types"]=sorted(doc_types.keys())
    elif(config_type=="sldl.export_labels"):
        labels=data.get("labels") if(isinstance(data.get("labels"), dict)) else {k:v for k,v in data.items() if(k not in {"config_type", "description", "html_lang", "version", "schema_version", "$schema"})}
        summary["labels"]=sorted(labels.keys())
    elif(config_type=="sldl.latex_build"):
        summary["dry_run"]=data.get("dry_run")
        summary["uses_steps"]=isinstance(data.get("steps"), list)
    elif(config_type=="sldl.template_manifest"):
        templates=data.get("templates") if(isinstance(data.get("templates"), list)) else []
        summary["templates"]=len(templates)
    elif(config_type=="sldl.template_reference"):
        templates=data.get("templates") if(isinstance(data.get("templates"), list)) else []
        summary["templates"]=len(templates)
    elif(config_type=="sldl.build_manifest"):
        documents=data.get("documents") if(isinstance(data.get("documents"), list)) else []
        summary["documents"]=len(documents)
    elif(config_type=="sldl.release_check"):
        summary["project_files"]=len(data.get("project_files", [])) if(isinstance(data.get("project_files"), list)) else 0
        summary["config_files"]=len(data.get("config_files", [])) if(isinstance(data.get("config_files"), list)) else 0
    elif(config_type=="sldl.release_manifest"):
        checks=data.get("checks") if(isinstance(data.get("checks"), list)) else []
        summary["checks"]=len(checks)
        summary["failed"]=(data.get("summary") or {}).get("failed") if(isinstance(data.get("summary"), dict)) else None
    elif(config_type=="sldl.snapshot_manifest"):
        files=data.get("files") if(isinstance(data.get("files"), list)) else []
        summary["files"]=len(files)
    return summary


def explain_config_type(config_type: str) -> str:
    if(config_type not in SUPPORTED_CONFIG_TYPES):
        raise ValueError(f"Unknown config type: {config_type}")
    spec=SUPPORTED_CONFIG_TYPES[config_type]
    lines=[f"# {config_type}", "", spec["title"], "", spec["description"], ""]
    lines.append("## Required keys")
    lines.append("")
    for key in spec["required"]:
        lines.append(f"- `{key}`")
    lines.append("")
    lines.append("## Important keys")
    lines.append("")
    for key in spec["important"]:
        lines.append(f"- `{key}`")
    lines.append("")
    lines.append("## Minimal example")
    lines.append("")
    lines.append("```json")
    lines.append(json.dumps(init_config_data(config_type), ensure_ascii=False, indent=2))
    lines.append("```")
    return "\n".join(lines)+"\n"

def explain_config_file(path: str | Path) -> str:
    summary=config_summary(path)
    config_type=summary.get("config_type")
    lines=[f"# Config file: {path}", "", f"- config_type: `{config_type or '-'}`", f"- description: {summary.get('description') or '-'}", f"- version: {summary.get('version') or '-'}", ""]
    diagnostics=check_config_file(path)
    lines.append("## Diagnostics")
    lines.append("")
    if(diagnostics):
        for diag in diagnostics:
            lines.append(f"- {diag.level.upper()} `{diag.code}`: {diag.message}")
    else:
        lines.append("- None")
    lines.append("")
    lines.append("## Top-level keys")
    lines.append("")
    for key in summary.get("top_level_keys", []):
        lines.append(f"- `{key}`")
    if(config_type in SUPPORTED_CONFIG_TYPES):
        lines.append("")
        lines.append("## Type reference")
        lines.append("")
        lines.append(SUPPORTED_CONFIG_TYPES[config_type]["description"])
    return "\n".join(lines)+"\n"


def init_config_data(config_type: str) -> dict[str, Any]:
    if(config_type=="sldl.project"):
        return {
            "config_type": "sldl.project",
            "description": "SLDL project build configuration.",
            "version": "1.0.0",
            "output_dir": "../build/official_examples",
            "citation_style": "author-year",
            "export_config": "export_labels_ja.json",
            "schemas": ["sldl_schema.json"],
            "toc": True,
            "mermaid_mode": "code",
            "documents": [
                {
                    "name": "official_project_overview_en",
                    "input": "official_project_overview_en.sldl",
                    "outputs": [
                        {"format": "markdown", "path": "../build/official_examples/official_project_overview_en.md"},
                        {"format": "latex", "path": "../build/official_examples/official_project_overview_en.tex"}
                    ]
                }
            ],
            "write_manifest": "../build/official_examples/sldl_build_manifest.json",
        }
    if(config_type=="sldl.schema"):
        return {
            "config_type": "sldl.schema",
            "description": "SLDL schema configuration.",
            "schema_version": "1.0.0",
            "document_types": {
                "SampleDocument": {
                    "required_blocks": ["meta"],
                    "allowed_top_level": ["meta", "section", "bibliography", "object"],
                    "allowed_node_kinds": ["Section", "Paragraph", "Reference"]
                }
            }
        }
    if(config_type=="sldl.export_labels"):
        return {
            "config_type": "sldl.export_labels",
            "description": "Japanese labels used by SLDL exporters.",
            "html_lang": "ja",
            "labels": {
                "author": "著者",
                "date": "日付",
                "version": "版",
                "toc": "目次",
                "claim": "主張",
                "evidence": "証拠",
                "references": "参考文献",
                "figure": "図",
                "table": "表",
                "listing": "リスト"
            }
        }
    if(config_type=="sldl.latex_build"):
        return {
            "config_type": "sldl.latex_build",
            "description": "pLaTeX + dvipdfmx build pipeline.",
            "version": "1.0.0",
            "dry_run": False,
            "capture_output": False,
            "timeout_sec": 120,
            "work_dir": "{tex_dir}",
            "output_dir": "{tex_dir}",
            "job_name": "{tex_stem}",
            "pdf_path": "{output_dir}/{job_name}.pdf",
            "stop_on_error": True,
            "show_output": False,
            "engine": {
                "name": "platex",
                "command": "platex",
                "passes": 2,
                "args": ["-interaction=nonstopmode", "-halt-on-error", "-file-line-error", "-output-directory", "{output_dir}", "{tex_path}"]
            },
            "dvi_to_pdf": {
                "enabled": True,
                "name": "dvipdfmx",
                "command": "dvipdfmx",
                "args": ["-o", "{pdf_path}", "{dvi_path}"]
            },
            "cleanup": {"enabled": False, "extensions": [".aux", ".log", ".dvi", ".toc", ".out"], "files": []}
        }
    if(config_type=="sldl.template_manifest"):
        return {
            "config_type": "sldl.template_manifest",
            "description": "SLDL template manifest with schema binding.",
            "version": "1.0.5",
            "templates": [
                {
                    "name": "sample",
                    "description": "Sample template",
                    "document_type": "SampleDocument",
                    "language": "en-US",
                    "path": "sample.sldl",
                    "schema": "../examples/sldl_schema.json",
                    "default_export_config": "../examples/export_labels_en.json",
                    "default_latex_build_config": "../examples/latex_build_platex_dvipdfmx_dry_run.json",
                    "strict_schema": True
                }
            ]
        }
    if(config_type=="sldl.build_manifest"):
        return {
            "config_type": "sldl.build_manifest",
            "description": "SLDL project build manifest.",
            "project": "project.json",
            "version": "1.0.0",
            "documents": []
        }
    if(config_type=="sldl.release_check"):
        return {
            "config_type": "sldl.release_check",
            "description": "SLDL release quality check target.",
            "version": "1.0.0",
            "base_dir": ".",
            "required_files": ["README.md", "CHANGELOG.md"],
            "forbidden_globs": ["examples/v0*", "docs/sldl_v0_*", "docs/v0_*", "tests/test_v0*.py"],
            "config_files": ["examples/sldl_schema.json", "examples/project_official_examples.json"],
            "commands": [{"name": "config-list", "args": ["config", "list"]}, {"name": "negative-example", "args": ["project", "check", "examples/invalid_project.json"], "expect_failure": True}],
            "project_files": ["examples/project_official_examples.json"],
            "build_project_files": ["examples/project_official_examples.json"],
            "build_manifest_files": ["build/official_examples/sldl_build_manifest.json"],
            "golden_snapshot": "examples/golden_snapshot.json",
            "compileall": True,
            "compile_paths": ["sldl_compiler"]
        }
    if(config_type=="sldl.release_manifest"):
        return {
            "config_type": "sldl.release_manifest",
            "description": "SLDL release quality check manifest.",
            "version": "1.0.0",
            "target": "examples/release_check.json",
            "base_dir": ".",
            "python": "python3",
            "checks": [],
            "summary": {"total": 0, "passed": 0, "failed": 0},
            "elapsed_sec": 0.0
        }
    if(config_type=="sldl.snapshot_manifest"):
        return {
            "config_type": "sldl.snapshot_manifest",
            "description": "SLDL golden file snapshot manifest.",
            "version": "1.0.0",
            "files": []
        }
    raise ValueError(f"Unknown config type: {config_type}")


def _check_common_metadata(data: dict[str, Any], config_type: str) -> list[Diagnostic]:
    diagnostics=[]
    if(data.get("config_type") != config_type):
        if("config_type" in data):
            diagnostics.append(Diagnostic("warning", "W_CONFIG_TYPE_NON_STRING", "config_type should be a non-empty string"))
    if("description" in data and not isinstance(data.get("description"), str)):
        diagnostics.append(Diagnostic("warning", "W_CONFIG_DESCRIPTION_TYPE", "description should be a string"))
    return diagnostics


def _check_project_config(data: dict[str, Any], base_dir: Path, check_paths: bool) -> list[Diagnostic]:
    diagnostics=[]
    documents=data.get("documents")
    if(not isinstance(documents, list) or not documents):
        diagnostics.append(Diagnostic("error", "E_PROJECT_DOCUMENTS", "sldl.project must contain a non-empty documents list"))
        return diagnostics
    _check_schema_refs(data, base_dir, diagnostics, check_paths, "project")
    _check_file_ref(data, "export_config", base_dir, diagnostics, check_paths, required=False)
    _check_file_ref(data, "latex_build_config", base_dir, diagnostics, check_paths, required=False)
    _check_latex_block(data.get("latex"), diagnostics, "latex")
    _check_mermaid_mode(data, diagnostics, "project")
    if("citation_style" in data and data.get("citation_style") not in KNOWN_CITATION_STYLES):
        diagnostics.append(Diagnostic("warning", "W_PROJECT_CITATION_STYLE", f"Unknown citation_style: {data.get('citation_style')}"))
    if("toc" in data and not isinstance(data.get("toc"), bool)):
        diagnostics.append(Diagnostic("error", "E_PROJECT_TOC_BOOL", "project.toc must be a boolean"))
    for i,doc in enumerate(documents):
        loc=f"documents[{i}]"
        if(not isinstance(doc, dict)):
            diagnostics.append(Diagnostic("error", "E_PROJECT_DOCUMENT", f"{loc} must be an object"))
            continue
        if("toc" in doc and not isinstance(doc.get("toc"), bool)):
            diagnostics.append(Diagnostic("error", "E_PROJECT_TOC_BOOL", f"{loc}.toc must be a boolean"))
        if(not isinstance(doc.get("input"), str) or not doc.get("input")):
            diagnostics.append(Diagnostic("error", "E_PROJECT_INPUT", f"{loc}.input must be a non-empty string"))
        elif(check_paths):
            _warn_missing_path(base_dir/doc["input"], diagnostics, f"{loc}.input")
        _check_schema_refs(doc, base_dir, diagnostics, check_paths, loc)
        _check_file_ref(doc, "export_config", base_dir, diagnostics, check_paths, required=False, prefix=loc)
        _check_file_ref(doc, "latex_build_config", base_dir, diagnostics, check_paths, required=False, prefix=loc)
        _check_latex_block(doc.get("latex"), diagnostics, f"{loc}.latex")
        _check_mermaid_mode(doc, diagnostics, loc)
        outputs=doc.get("outputs", data.get("outputs", []))
        if(outputs is None):
            outputs=[]
        if(not isinstance(outputs, list)):
            diagnostics.append(Diagnostic("error", "E_PROJECT_OUTPUTS", f"{loc}.outputs must be a list"))
            continue
        for j,out in enumerate(outputs):
            out_loc=f"{loc}.outputs[{j}]"
            if(not isinstance(out, dict)):
                diagnostics.append(Diagnostic("error", "E_PROJECT_OUTPUT", f"{out_loc} must be an object"))
                continue
            fmt=str(out.get("format", "json"))
            if(fmt not in KNOWN_OUTPUT_FORMATS):
                diagnostics.append(Diagnostic("error", "E_PROJECT_OUTPUT_FORMAT", f"Unsupported output format at {out_loc}: {fmt}"))
            if("path" in out and not isinstance(out.get("path"), str)):
                diagnostics.append(Diagnostic("error", "E_PROJECT_OUTPUT_PATH", f"{out_loc}.path must be a string"))
            if("toc" in out and not isinstance(out.get("toc"), bool)):
                diagnostics.append(Diagnostic("error", "E_PROJECT_TOC_BOOL", f"{out_loc}.toc must be a boolean"))
            _check_file_ref(out, "export_config", base_dir, diagnostics, check_paths, required=False, prefix=out_loc)
            _check_file_ref(out, "latex_build_config", base_dir, diagnostics, check_paths, required=False, prefix=out_loc)
            _check_latex_block(out.get("latex"), diagnostics, f"{out_loc}.latex")
            _check_mermaid_mode(out, diagnostics, out_loc)
    return diagnostics


def _check_schema_refs(data: dict[str, Any], base_dir: Path, diagnostics: list[Diagnostic], check_paths: bool, prefix: str) -> None:
    if("schema" in data):
        if(not isinstance(data.get("schema"), str)):
            diagnostics.append(Diagnostic("error", "E_PROJECT_SCHEMA", f"{prefix}.schema must be a string"))
        elif(check_paths):
            _warn_missing_path(base_dir/data["schema"], diagnostics, f"{prefix}.schema")
    if("schemas" in data):
        schemas=data.get("schemas")
        if(not isinstance(schemas, list)):
            diagnostics.append(Diagnostic("error", "E_PROJECT_SCHEMAS", f"{prefix}.schemas must be a list of strings"))
        else:
            for i,item in enumerate(schemas):
                if(not isinstance(item, str)):
                    diagnostics.append(Diagnostic("error", "E_PROJECT_SCHEMA", f"{prefix}.schemas[{i}] must be a string"))
                elif(check_paths):
                    _warn_missing_path(base_dir/item, diagnostics, f"{prefix}.schemas[{i}]")


def _check_file_ref(data: dict[str, Any], key: str, base_dir: Path, diagnostics: list[Diagnostic], check_paths: bool, required: bool = False, prefix: str = "project") -> None:
    if(key not in data):
        if(required):
            diagnostics.append(Diagnostic("error", "E_CONFIG_PATH_REQUIRED", f"{prefix}.{key} is required"))
        return
    value=data.get(key)
    if(value is None):
        return
    if(not isinstance(value, str)):
        diagnostics.append(Diagnostic("error", "E_CONFIG_PATH_TYPE", f"{prefix}.{key} must be a string"))
        return
    if(check_paths):
        _warn_missing_path(base_dir/value, diagnostics, f"{prefix}.{key}")


def _check_export_labels_config(data: dict[str, Any]) -> list[Diagnostic]:
    diagnostics=[]
    if("html_lang" in data and not isinstance(data.get("html_lang"), str)):
        diagnostics.append(Diagnostic("error", "E_EXPORT_LABELS_HTML_LANG", "html_lang must be a string"))
    labels=data.get("labels")
    if(labels is not None):
        if(not isinstance(labels, dict)):
            diagnostics.append(Diagnostic("error", "E_EXPORT_LABELS_LABELS", "labels must be an object"))
        else:
            for key,value in labels.items():
                if(not isinstance(key, str) or not isinstance(value, str)):
                    diagnostics.append(Diagnostic("error", "E_EXPORT_LABELS_VALUE", "labels entries must be string-to-string"))
    else:
        for key,value in data.items():
            if(key in {"config_type", "description", "html_lang", "version", "schema_version", "$schema", "name"}):
                continue
            if(not isinstance(value, str)):
                diagnostics.append(Diagnostic("warning", "W_EXPORT_LABELS_VALUE", f"Top-level label {key} should be a string"))
    return diagnostics


def _check_latex_build_config(data: dict[str, Any]) -> list[Diagnostic]:
    diagnostics=[]
    for key in ("dry_run", "stop_on_error", "show_output"):
        if(key in data and not isinstance(data.get(key), bool)):
            diagnostics.append(Diagnostic("error", "E_LATEX_BUILD_BOOL", f"{key} must be a boolean"))
    steps=data.get("steps")
    if(steps is not None):
        if(not isinstance(steps, list)):
            diagnostics.append(Diagnostic("error", "E_LATEX_BUILD_STEPS", "steps must be a list"))
        else:
            for i,step in enumerate(steps):
                _check_latex_step(step, diagnostics, f"steps[{i}]")
    engine=data.get("engine")
    if(engine is not None):
        if(not isinstance(engine, dict)):
            diagnostics.append(Diagnostic("error", "E_LATEX_BUILD_ENGINE", "engine must be an object"))
        else:
            if(engine.get("enabled", True)):
                _check_command_object(engine, diagnostics, "engine")
            if("passes" in engine and not isinstance(engine.get("passes"), int)):
                diagnostics.append(Diagnostic("error", "E_LATEX_BUILD_PASSES", "engine.passes must be an integer"))
    dvi=data.get("dvi_to_pdf")
    if(dvi is not None):
        if(not isinstance(dvi, dict)):
            diagnostics.append(Diagnostic("error", "E_LATEX_BUILD_DVI", "dvi_to_pdf must be an object"))
        elif(dvi.get("enabled", True)):
            _check_command_object(dvi, diagnostics, "dvi_to_pdf")
    cleanup=data.get("cleanup")
    if(cleanup is not None):
        if(not isinstance(cleanup, dict)):
            diagnostics.append(Diagnostic("error", "E_LATEX_BUILD_CLEANUP", "cleanup must be an object"))
        else:
            if("enabled" in cleanup and not isinstance(cleanup.get("enabled"), bool)):
                diagnostics.append(Diagnostic("error", "E_LATEX_BUILD_CLEANUP_BOOL", "cleanup.enabled must be a boolean"))
            for key in ("extensions", "files"):
                if(key in cleanup and not _is_string_list(cleanup.get(key))):
                    diagnostics.append(Diagnostic("error", "E_LATEX_BUILD_CLEANUP_LIST", f"cleanup.{key} must be a list of strings"))
    return diagnostics


def _check_latex_step(step: Any, diagnostics: list[Diagnostic], prefix: str) -> None:
    if(not isinstance(step, dict)):
        diagnostics.append(Diagnostic("error", "E_LATEX_BUILD_STEP", f"{prefix} must be an object"))
        return
    _check_command_object(step, diagnostics, prefix)
    if("repeat" in step and not isinstance(step.get("repeat"), int)):
        diagnostics.append(Diagnostic("error", "E_LATEX_BUILD_REPEAT", f"{prefix}.repeat must be an integer"))


def _check_command_object(obj: dict[str, Any], diagnostics: list[Diagnostic], prefix: str) -> None:
    if(not isinstance(obj.get("command"), str) or not str(obj.get("command")).strip()):
        diagnostics.append(Diagnostic("error", "E_LATEX_BUILD_COMMAND", f"{prefix}.command must be a non-empty string"))
    if("args" in obj and not (isinstance(obj.get("args"), list) or isinstance(obj.get("args"), str))):
        diagnostics.append(Diagnostic("error", "E_LATEX_BUILD_ARGS", f"{prefix}.args must be a list or string"))
    if(isinstance(obj.get("args"), list) and not all(isinstance(x, (str, int, float, bool)) for x in obj.get("args"))):
        diagnostics.append(Diagnostic("error", "E_LATEX_BUILD_ARGS", f"{prefix}.args list items must be scalar values"))


def _check_template_manifest(data: dict[str, Any], base_dir: Path, check_paths: bool, manifest_path: Path | None = None) -> list[Diagnostic]:
    diagnostics=[]
    templates=data.get("templates")
    if(isinstance(templates, dict)):
        template_items=[]
        for name,value in templates.items():
            if(isinstance(value, dict)):
                item=dict(value)
                item.setdefault("name", str(name))
                template_items.append(item)
            else:
                diagnostics.append(Diagnostic("error", "E_TEMPLATE_MANIFEST_TEMPLATE", f"templates.{name} must be an object"))
        templates=template_items
    if(not isinstance(templates, list) or not templates):
        diagnostics.append(Diagnostic("error", "E_TEMPLATE_MANIFEST_TEMPLATES", "templates must be a non-empty list or object"))
        return diagnostics
    manifest_role=data.get("manifest_role")
    if(manifest_role is not None and manifest_role not in {"canonical", "legacy_compatibility", "adhoc"}):
        diagnostics.append(Diagnostic("error", "E_TEMPLATE_MANIFEST_ROLE", "manifest_role must be canonical, legacy_compatibility, or adhoc"))
    if(manifest_path is not None and manifest_path.name=="manifest.json"):
        diagnostics.append(Diagnostic("warning", "W_TEMPLATE_MANIFEST_LEGACY", "templates/manifest.json is a legacy compatibility copy; templates/template_manifest.json is canonical in v1.0.5"))
        canonical_value=data.get("canonical_manifest")
        if(canonical_value is not None and canonical_value!="template_manifest.json"):
            diagnostics.append(Diagnostic("error", "E_TEMPLATE_MANIFEST_CANONICAL", "legacy manifest canonical_manifest must be template_manifest.json"))
    if(manifest_path is not None and manifest_path.name=="template_manifest.json" and manifest_role=="legacy_compatibility"):
        diagnostics.append(Diagnostic("error", "E_TEMPLATE_MANIFEST_ROLE", "template_manifest.json must not be marked as legacy_compatibility"))
    allowed_keys={
        "name", "description", "document_type", "language", "path", "template_file",
        "schema", "default_export_config", "default_latex_build_config", "strict_schema"
    }
    seen=set()
    for i,item in enumerate(templates):
        loc=f"templates[{i}]"
        if(not isinstance(item, dict)):
            diagnostics.append(Diagnostic("error", "E_TEMPLATE_MANIFEST_TEMPLATE", f"{loc} must be an object"))
            continue
        for key in item.keys():
            if(key not in allowed_keys):
                diagnostics.append(Diagnostic("warning", "W_TEMPLATE_MANIFEST_UNKNOWN_KEY", f"{loc}.{key} is not a known template manifest field"))
        for key in ("name", "description", "document_type", "language"):
            if(not isinstance(item.get(key), str) or not item.get(key)):
                diagnostics.append(Diagnostic("error", "E_TEMPLATE_MANIFEST_FIELD", f"{loc}.{key} must be a non-empty string"))
        path_value=item.get("path", item.get("template_file"))
        if(not isinstance(path_value, str) or not path_value):
            diagnostics.append(Diagnostic("error", "E_TEMPLATE_MANIFEST_FIELD", f"{loc}.path must be a non-empty string"))
        elif(check_paths):
            _warn_missing_path(base_dir/path_value, diagnostics, f"{loc}.path")
        name=item.get("name")
        if(isinstance(name, str)):
            if(name in seen):
                diagnostics.append(Diagnostic("error", "E_TEMPLATE_MANIFEST_DUPLICATE", f"duplicate template name: {name}"))
            seen.add(name)
        for key in ("schema", "default_export_config", "default_latex_build_config"):
            value=item.get(key)
            if(value is None):
                continue
            if(not isinstance(value, str) or not value):
                diagnostics.append(Diagnostic("error", "E_TEMPLATE_MANIFEST_FIELD", f"{loc}.{key} must be a non-empty string"))
            elif(check_paths):
                _warn_missing_path(base_dir/value, diagnostics, f"{loc}.{key}")
        if("strict_schema" in item and not isinstance(item.get("strict_schema"), bool)):
            diagnostics.append(Diagnostic("error", "E_TEMPLATE_MANIFEST_STRICT_SCHEMA", f"{loc}.strict_schema must be a boolean"))
        if(check_paths):
            _check_template_manifest_bound_file_types(item, base_dir, diagnostics, loc)
    if(check_paths):
        listed_paths=set()
        for item in templates:
            if(isinstance(item, dict)):
                path_value=item.get("path", item.get("template_file"))
                if(isinstance(path_value, str) and path_value):
                    listed_paths.add((base_dir/path_value).resolve())
        for sldl_path in sorted(base_dir.glob("*.sldl")):
            if(sldl_path.resolve() not in listed_paths):
                diagnostics.append(Diagnostic("warning", "W_TEMPLATE_MANIFEST_UNLISTED_TEMPLATE", f"template file is not listed in manifest: {sldl_path.name}"))
        if(manifest_path is not None):
            sibling_name="manifest.json" if(manifest_path.name=="template_manifest.json") else "template_manifest.json"
            sibling=manifest_path.parent/sibling_name
            if(sibling.exists()):
                sibling_data,sibling_diags=load_config_json(sibling)
                for diag in sibling_diags:
                    diagnostics.append(Diagnostic(diag.level, diag.code, f"{sibling.name}: {diag.message}", diag.line, diag.column))
                if(isinstance(sibling_data, dict) and _template_manifest_signature(data)!=_template_manifest_signature(sibling_data)):
                    diagnostics.append(Diagnostic("error", "E_TEMPLATE_MANIFEST_COMPATIBILITY", f"{manifest_path.name} and {sibling.name} declare different template sets"))
    return diagnostics


def _template_manifest_signature(data: dict[str, Any]) -> list[tuple[str, str, str, str]]:
    templates=data.get("templates")
    if(isinstance(templates, dict)):
        items=[]
        for name,value in templates.items():
            if(isinstance(value, dict)):
                item=dict(value)
                item.setdefault("name", str(name))
                items.append(item)
    elif(isinstance(templates, list)):
        items=[item for item in templates if(isinstance(item, dict))]
    else:
        items=[]
    signature=[]
    for item in items:
        signature.append((
            str(item.get("name", "")),
            str(item.get("path", item.get("template_file", ""))),
            str(item.get("document_type", "")),
            str(item.get("schema", "")),
        ))
    return sorted(signature)


def _check_template_manifest_bound_file_types(item: dict[str, Any], base_dir: Path, diagnostics: list[Diagnostic], loc: str) -> None:
    expected={
        "schema": "sldl.schema",
        "default_export_config": "sldl.export_labels",
        "default_latex_build_config": "sldl.latex_build",
    }
    loaded: dict[str, dict[str, Any]]={}
    for key,expected_type in expected.items():
        value=item.get(key)
        if(not isinstance(value, str) or not value):
            continue
        path=base_dir/value
        if(not path.exists()):
            continue
        data,sub_diags=load_config_json(path)
        if(data is None):
            for diag in sub_diags:
                diagnostics.append(Diagnostic(diag.level, diag.code, f"{loc}.{key}: {diag.message}", diag.line, diag.column))
            continue
        config_type,inferred_diag=detect_config_type(data)
        if(inferred_diag and inferred_diag.level=="error"):
            diagnostics.append(Diagnostic("error", inferred_diag.code, f"{loc}.{key}: {inferred_diag.message}"))
        if(config_type!=expected_type):
            diagnostics.append(Diagnostic("error", "E_TEMPLATE_MANIFEST_BOUND_CONFIG_TYPE", f"{loc}.{key} must reference {expected_type}, got {config_type or '-'}"))
        loaded[key]=data
    schema_data=loaded.get("schema")
    document_type=item.get("document_type")
    if(schema_data is not None and isinstance(document_type, str) and document_type):
        document_types=schema_data.get("document_types")
        if(not isinstance(document_types, dict) or document_type not in document_types):
            diagnostics.append(Diagnostic("error", "E_TEMPLATE_SCHEMA_DOCUMENT_TYPE", f"{loc}.document_type {document_type} is not defined by the bound schema"))


def _check_template_reference(data: dict[str, Any]) -> list[Diagnostic]:
    diagnostics=[]
    templates=data.get("templates")
    if(not isinstance(templates, list) or not templates):
        diagnostics.append(Diagnostic("error", "E_TEMPLATE_REFERENCE_TEMPLATES", "templates must be a non-empty list"))
        return diagnostics
    seen=set()
    for i,item in enumerate(templates):
        loc=f"templates[{i}]"
        if(not isinstance(item, dict)):
            diagnostics.append(Diagnostic("error", "E_TEMPLATE_REFERENCE_TEMPLATE", f"{loc} must be an object"))
            continue
        name=item.get("name")
        if(not isinstance(name, str) or not name):
            diagnostics.append(Diagnostic("error", "E_TEMPLATE_REFERENCE_NAME", f"{loc}.name must be a non-empty string"))
        elif(name in seen):
            diagnostics.append(Diagnostic("error", "E_TEMPLATE_REFERENCE_DUPLICATE", f"duplicate template name: {name}"))
        else:
            seen.add(name)
        for key in ("document_type", "language", "schema", "manifest_role"):
            if(key in item and item.get(key) is not None and not isinstance(item.get(key), str)):
                diagnostics.append(Diagnostic("error", "E_TEMPLATE_REFERENCE_FIELD", f"{loc}.{key} must be a string or null"))
    return diagnostics


def _check_build_manifest(data: dict[str, Any]) -> list[Diagnostic]:
    diagnostics=[]
    documents=data.get("documents")
    if(not isinstance(documents, list)):
        diagnostics.append(Diagnostic("error", "E_BUILD_MANIFEST_DOCUMENTS", "documents must be a list"))
        return diagnostics
    for i,doc in enumerate(documents):
        if(not isinstance(doc, dict)):
            diagnostics.append(Diagnostic("error", "E_BUILD_MANIFEST_DOCUMENT", f"documents[{i}] must be an object"))
            continue
        if("outputs" in doc and not isinstance(doc.get("outputs"), list)):
            diagnostics.append(Diagnostic("error", "E_BUILD_MANIFEST_OUTPUTS", f"documents[{i}].outputs must be a list"))
        if("template" in doc and doc.get("template") is not None):
            template=doc.get("template")
            if(not isinstance(template, dict)):
                diagnostics.append(Diagnostic("error", "E_BUILD_MANIFEST_TEMPLATE", f"documents[{i}].template must be an object or null"))
            else:
                for key in ("name", "source", "manifest", "manifest_role", "declared_document_type", "schema", "export_config", "latex_build_config", "source_sha256", "manifest_sha256", "schema_sha256", "export_config_sha256", "latex_build_config_sha256"):
                    if(key in template and template.get(key) is not None and not isinstance(template.get(key), str)):
                        diagnostics.append(Diagnostic("error", "E_BUILD_MANIFEST_TEMPLATE_FIELD", f"documents[{i}].template.{key} must be a string or null"))
    return diagnostics


def _check_release_check_config(data: dict[str, Any], base_dir: Path, check_paths: bool) -> list[Diagnostic]:
    diagnostics=[]
    if("base_dir" in data and not isinstance(data.get("base_dir"), str)):
        diagnostics.append(Diagnostic("error", "E_RELEASE_BASE_DIR", "base_dir must be a string"))
    actual_base=base_dir
    if(isinstance(data.get("base_dir"), str)):
        value=Path(data["base_dir"])
        actual_base=value if(value.is_absolute()) else base_dir/value
    for key in ("required_files", "forbidden_paths", "forbidden_globs", "config_files", "project_files", "build_project_files", "build_manifest_files", "compile_paths"):
        value=data.get(key)
        if(value is None):
            continue
        if(not _is_string_list(value)):
            diagnostics.append(Diagnostic("error", "E_RELEASE_LIST", f"{key} must be a list of strings"))
            continue
        if(check_paths and key not in {"build_manifest_files", "forbidden_paths", "forbidden_globs"}):
            for i,item in enumerate(value):
                _warn_missing_path(actual_base/item, diagnostics, f"{key}[{i}]")
    if("compileall" in data and not isinstance(data.get("compileall"), bool)):
        diagnostics.append(Diagnostic("error", "E_RELEASE_COMPILEALL", "compileall must be a boolean"))
    commands=data.get("commands")
    if(commands is not None):
        if(not isinstance(commands, list)):
            diagnostics.append(Diagnostic("error", "E_RELEASE_COMMANDS", "commands must be a list"))
        else:
            for i,command in enumerate(commands):
                if(not isinstance(command, dict)):
                    diagnostics.append(Diagnostic("error", "E_RELEASE_COMMAND", f"commands[{i}] must be an object"))
                    continue
                if("args" not in command or not _is_string_list(command.get("args"))):
                    diagnostics.append(Diagnostic("error", "E_RELEASE_COMMAND_ARGS", f"commands[{i}].args must be a list of strings"))
                if("expect_failure" in command and not isinstance(command.get("expect_failure"), bool)):
                    diagnostics.append(Diagnostic("error", "E_RELEASE_COMMAND_EXPECT_FAILURE", f"commands[{i}].expect_failure must be a boolean"))
    snapshot=data.get("golden_snapshot")
    if(snapshot is not None):
        if(not isinstance(snapshot, str)):
            diagnostics.append(Diagnostic("error", "E_RELEASE_SNAPSHOT", "golden_snapshot must be a string"))
        elif(check_paths):
            _warn_missing_path(actual_base/snapshot, diagnostics, "golden_snapshot")
    return diagnostics


def _check_release_manifest(data: dict[str, Any]) -> list[Diagnostic]:
    diagnostics=[]
    checks=data.get("checks")
    if(not isinstance(checks, list)):
        diagnostics.append(Diagnostic("error", "E_RELEASE_MANIFEST_CHECKS", "checks must be a list"))
    else:
        for i,item in enumerate(checks):
            if(not isinstance(item, dict)):
                diagnostics.append(Diagnostic("error", "E_RELEASE_MANIFEST_CHECK", f"checks[{i}] must be an object"))
                continue
            if("ok" in item and not isinstance(item.get("ok"), bool)):
                diagnostics.append(Diagnostic("error", "E_RELEASE_MANIFEST_OK", f"checks[{i}].ok must be a boolean"))
    summary=data.get("summary")
    if(not isinstance(summary, dict)):
        diagnostics.append(Diagnostic("error", "E_RELEASE_MANIFEST_SUMMARY", "summary must be an object"))
    return diagnostics


def _check_snapshot_manifest(data: dict[str, Any], base_dir: Path, check_paths: bool) -> list[Diagnostic]:
    diagnostics=[]
    files=data.get("files")
    if(not isinstance(files, list)):
        diagnostics.append(Diagnostic("error", "E_SNAPSHOT_FILES", "files must be a list"))
        return diagnostics
    for i,item in enumerate(files):
        loc=f"files[{i}]"
        if(not isinstance(item, dict)):
            diagnostics.append(Diagnostic("error", "E_SNAPSHOT_FILE", f"{loc} must be an object"))
            continue
        if(not isinstance(item.get("path"), str) or not item.get("path")):
            diagnostics.append(Diagnostic("error", "E_SNAPSHOT_PATH", f"{loc}.path must be a non-empty string"))
        elif(check_paths):
            _warn_missing_path(base_dir/item["path"], diagnostics, f"{loc}.path")
        if(not isinstance(item.get("sha256"), str) or len(item.get("sha256", ""))!=64):
            diagnostics.append(Diagnostic("error", "E_SNAPSHOT_SHA256", f"{loc}.sha256 must be a SHA-256 hex string"))
        if("bytes" in item and not isinstance(item.get("bytes"), int)):
            diagnostics.append(Diagnostic("error", "E_SNAPSHOT_BYTES", f"{loc}.bytes must be an integer"))
    return diagnostics


def _check_latex_block(value: Any, diagnostics: list[Diagnostic], prefix: str) -> None:
    if(value is None):
        return
    if(not isinstance(value, dict)):
        diagnostics.append(Diagnostic("error", "E_LATEX_OPTIONS", f"{prefix} must be an object"))
        return
    for key,item in value.items():
        if(key not in KNOWN_LATEX_KEYS):
            diagnostics.append(Diagnostic("warning", "W_LATEX_OPTION_UNKNOWN", f"Unknown LaTeX option at {prefix}: {key}"))
        if(key in {"hyperref", "sloppy", "toc", "latex_hyperref", "latex_sloppy", "latex_toc"} and not isinstance(item, bool)):
            diagnostics.append(Diagnostic("error", "E_LATEX_OPTION_BOOL", f"{prefix}.{key} must be a boolean"))
        if(key in {"table_font", "latex_table_font", "code_font_size", "latex_code_font_size"} and item not in KNOWN_TABLE_FONT_VALUES):
            diagnostics.append(Diagnostic("warning", "W_LATEX_OPTION_VALUE", f"Unexpected value for {prefix}.{key}: {item}"))
        if(key in {"top_level", "latex_top_level"} and item not in KNOWN_TOP_LEVEL_VALUES):
            diagnostics.append(Diagnostic("warning", "W_LATEX_OPTION_VALUE", f"Unexpected value for {prefix}.{key}: {item}"))
        if(key in {"code_environment", "latex_code_environment"} and item not in KNOWN_CODE_ENV_VALUES):
            diagnostics.append(Diagnostic("warning", "W_LATEX_OPTION_VALUE", f"Unexpected value for {prefix}.{key}: {item}"))
        if(key in {"mermaid_mode", "latex_mermaid_mode"} and item not in KNOWN_MERMAID_MODE_VALUES):
            diagnostics.append(Diagnostic("warning", "W_LATEX_OPTION_VALUE", f"Unexpected value for {prefix}.{key}: {item}"))


def _check_mermaid_mode(data: dict[str, Any], diagnostics: list[Diagnostic], prefix: str) -> None:
    if("mermaid_mode" in data and data.get("mermaid_mode") not in KNOWN_MERMAID_MODE_VALUES):
        diagnostics.append(Diagnostic("warning", "W_PROJECT_MERMAID_MODE", f"Unexpected value for {prefix}.mermaid_mode: {data.get('mermaid_mode')}"))


def _warn_missing_path(path: Path, diagnostics: list[Diagnostic], label: str) -> None:
    if(not path.exists()):
        diagnostics.append(Diagnostic("warning", "W_CONFIG_PATH_MISSING", f"Referenced path for {label} does not exist: {path}"))


def _is_string_list(value: Any) -> bool:
    return isinstance(value, list) and all(isinstance(item, str) for item in value)
